import { describe, expect, it } from 'vitest'
import { annualDebtService, buildCompanyFinancialSnapshot } from './companyFinancialSummary.js'
const p = (id, value = 200000, rent = 1000) => ({ id, name: id, active: true, latestValuation: value, rent })
const l = (id, propertyId, balance, rate, interestOnly = true) => ({ id, propertyId, currentBalance: balance, principalAmount: balance, rate, interestOnly, termMonths: 300, fixedRateMonths: 60, fixedStartDate: '2025-01-01' })
const base = { company: { registeredName: 'Test SPV Ltd', companyNumber: 'SC123456', shareholders: [{ name: 'A', percentage: 100 }] }, settings: { cashHeld: 20000 }, tenants: [], transactions: [], reportingDate: '2026-09-09', periodStart: '2025-09-10' }
describe('company financial summary', () => {
  it('includes every mortgage and uses aggregate rather than average LTV', () => { const s = buildCompanyFinancialSnapshot({ ...base, properties: [p('A', 300000), p('B', 100000)], loans: [l('1','A',120000,.04), l('2','A',30000,.06), l('3','B',50000,.05)] }); expect(s.portfolio.mortgageDebt).toBe(200000); expect(s.portfolio.aggregateLtv).toBeCloseTo(.5); expect(s.portfolio.grossPropertyEquity).toBe(200000); expect(s.portfolio.weightedRate).toBeCloseTo(.0475) })
  it('handles zero debt safely', () => { const s = buildCompanyFinancialSnapshot({ ...base, properties: [p('A')], loans: [] }); expect(s.portfolio.aggregateLtv).toBe(0); expect(s.portfolio.weightedRate).toBe(0); expect(s.resilience.icr).toBe(null) })
  it('keeps actual banking separate from annualised theoretical values and excludes transfers/financing', () => { const tx = [{ amount: 1000, category:'rent', bookedAt:'2026-08-01' }, { amount:-100, category:'repairs', bookedAt:'2026-08-02' }, { amount:5000, category:'transfer', bookedAt:'2026-08-03' }, { amount:-90000, category:'mortgage', bookedAt:'2026-08-04' }]; const s = buildCompanyFinancialSnapshot({ ...base, properties:[p('A',200000,1200)], loans:[l('1','A',100000,.05)], transactions:tx }); expect(s.actual.operatingIncome).toBe(1000); expect(s.actual.netCashFlow).toBe(900); expect(s.actual.debtServiceCash).toBe(90000); expect(s.runRate.annualRent).toBe(14400) })
  it('does not treat positive mortgage funding as debt-service cash', () => { const tx = [{ amount:90000, category:'mortgage', bookedAt:'2026-08-04' }]; const s = buildCompanyFinancialSnapshot({ ...base, properties:[p('A')], loans:[l('1','A',100000,.05)], transactions:tx }); expect(s.actual.debtServiceCash).toBe(0); expect(s.actual.operatingIncome).toBe(0); expect(s.actual.operatingOutflow).toBe(0) })
  it('does not double count owner extractions when excluded', () => { const tx = [{ amount:-500, category:'cash_extraction', bookedAt:'2026-08-01' }]; const s = buildCompanyFinancialSnapshot({ ...base, properties:[p('A')], loans:[], transactions:tx, includeExtractions:false }); expect(s.actual.operatingOutflow).toBe(0) })
  it('calculates IO and repayment debt service through authoritative loan maths', () => { expect(annualDebtService([l('1','A',120000,.06,true)])).toBeCloseTo(7200); expect(annualDebtService([l('2','A',120000,.06,false)])).toBeGreaterThan(7200) })
  it('flags missing values rather than treating them as verified zeroes', () => { const s = buildCompanyFinancialSnapshot({ ...base, company:{registeredName:'X'}, properties:[p('A',0,0)], loans:[] }); expect(s.warnings.join(' ')).toMatch(/valuation is missing/); expect(s.warnings.join(' ')).toMatch(/current rent is missing/); expect(s.warnings.join(' ')).toMatch(/registration number is missing/) })
  it('computes cash buffer and stressed ICR numerically', () => { const s = buildCompanyFinancialSnapshot({ ...base, properties:[p('A',200000,2000)], loans:[l('1','A',100000,.05)] }); expect(s.resilience.bufferMonths).toBeGreaterThan(0); expect(s.resilience.stressedIcr).toBeLessThan(s.resilience.icr) })
})
