export const assumptions = {
  appreciationRate: 0.03,
  rateShock: 0.007,
  corporationTaxRate: 0.19,
  managementRate: 0.12,
  cashHeld: 12700,
  bufferMonths: 6,
  projectionMonths: 60,
  vladLoanValue: 49551,
  vladLoanTermMonths: 120,
  vladLoanRate: 0.06,
  landlordRegistration: '540076/260/18032',
}

const sharedCosts = {
  legionella: 66 / 24,
  gasCertificate: 100 / 12,
  eicr: 150 / 60,
  repairs: 50,
  applianceReserve: (400 + 250 + 100 + 150) / 60,
}

export const seedProperties = [
  {
    id: 'btl-1',
    name: 'BTL1',
    address: '130 Kelvinhaugh Street',
    postcode: 'G3 8PP',
    flatNumber: '2/2',
    purchasePrice: 205000,
    homeReportPurchase: 235000,
    latestValuation: 261924,
    loanAmount: 181587,
    areaSqm: 76,
    bedrooms: 3,
    epc: 'B (82)',
    rent: 1650,
    purchaseDate: '2020-12-19',
    lender: 'Paragon',
    mortgageNumber: '',
    baseRate: 0.045,
    fixedRateMonths: 24,
    factorsFees: 150,
    tenantName: '',
    tenantEmail: '',
    tenantPhone: '',
    tenantOccupation: '',
    tenantMoveIn: '2024-01-06',
    depositHeld: 'SafeDeposits Scotland',
    latestRemortgage: '2025-02-28',
    gasExpiry: '2026-08-20',
    eicrExpiry: '2028-08-30',
    epcExpiry: '2030-10-28',
    patExpiry: '2026-08-20',
    engineeredCost: 925,
    active: true,
    ...sharedCosts,
  },
  {
    id: 'btl-2',
    name: 'BTL2',
    address: '20 Rutland Court',
    postcode: 'G51 1LZ',
    flatNumber: '3/2',
    purchasePrice: 148000,
    homeReportPurchase: 145000,
    latestValuation: 150018,
    loanAmount: 112307,
    areaSqm: 58,
    bedrooms: 2,
    epc: 'C (72)',
    rent: 1100,
    purchaseDate: '2025-08-29',
    lender: 'The Mortgage Works',
    mortgageNumber: '',
    baseRate: 0.045,
    fixedRateMonths: 24,
    factorsFees: 90,
    tenantName: '',
    tenantEmail: '',
    tenantPhone: '',
    tenantOccupation: '',
    tenantMoveIn: '2026-06-16',
    depositHeld: 'SafeDeposits Scotland',
    latestRemortgage: '2025-08-01',
    gasExpiry: '2026-10-07',
    eicrExpiry: '2026-10-07',
    epcExpiry: '2035-06-19',
    patExpiry: '2027-10-07',
    engineeredCost: 0,
    active: true,
    ...sharedCosts,
  },
  {
    id: 'btl-3',
    name: 'BTL3',
    address: '10 Rutland Court',
    postcode: 'G51 1JW',
    flatNumber: '2/2',
    purchasePrice: 185000,
    homeReportPurchase: 184000,
    latestValuation: 184000,
    loanAmount: 138750,
    areaSqm: 58,
    bedrooms: 2,
    epc: 'C (72)',
    rent: 1100,
    purchaseDate: '2025-08-29',
    lender: 'The Mortgage Works',
    mortgageNumber: '',
    baseRate: 0.045,
    fixedRateMonths: 24,
    factorsFees: 90,
    tenantName: '',
    tenantEmail: '',
    tenantPhone: '',
    tenantOccupation: '',
    tenantMoveIn: '',
    depositHeld: '',
    latestRemortgage: '2024-11-20',
    gasExpiry: '2026-10-07',
    eicrExpiry: '2026-10-07',
    epcExpiry: '2035-06-19',
    patExpiry: '2027-10-07',
    engineeredCost: 0,
    active: true,
    ...sharedCosts,
  },
]

export const editableSections = [
  {
    title: 'Property',
    fields: [
      ['name', 'BTL name', 'text'], ['address', 'Street address', 'text'],
      ['postcode', 'Postcode', 'text'], ['flatNumber', 'Flat number', 'text'],
      ['purchasePrice', 'Purchase price', 'number'], ['homeReportPurchase', 'Home report at purchase', 'number'],
      ['latestValuation', 'Latest valuation', 'number'], ['loanAmount', 'Loan amount', 'number'],
      ['areaSqm', 'Area (m²)', 'number'], ['bedrooms', 'Bedrooms', 'number'],
      ['epc', 'EPC', 'text'], ['rent', 'Monthly rent', 'number'], ['purchaseDate', 'First purchased', 'date'],
    ],
  },
  {
    title: 'Loan & costs',
    fields: [
      ['lender', 'Current lender', 'text'], ['mortgageNumber', 'Mortgage reference (private)', 'text'],
      ['baseRate', 'Base interest rate', 'percent'], ['fixedRateMonths', 'Fixed period (months)', 'number'],
      ['factorsFees', 'Factors fees / month', 'number'], ['repairs', 'Repairs reserve / month', 'number'],
      ['latestRemortgage', 'Latest remortgage', 'date'],
    ],
  },
  {
    title: 'Compliance dates',
    fields: [
      ['gasExpiry', 'Gas certificate expiry', 'date'], ['eicrExpiry', 'EICR expiry', 'date'],
      ['epcExpiry', 'EPC expiry', 'date'], ['patExpiry', 'PAT expiry', 'date'],
    ],
  },
  {
    title: 'Tenant (kept locally)',
    fields: [
      ['tenantName', 'Name', 'text'], ['tenantEmail', 'Email', 'email'],
      ['tenantPhone', 'Phone', 'tel'], ['tenantOccupation', 'Occupation', 'text'],
      ['tenantMoveIn', 'Move-in date', 'date'], ['depositHeld', 'Deposit held', 'text'],
    ],
  },
]
