import React, { useEffect, useMemo, useRef, useState } from 'react'
import {
  ArrowDownRight,
  ArrowUpRight,
  CircleHelp,
  Landmark,
  ShieldCheck,
  TrendingUp,
  X,
} from 'lucide-react'
import { currency, percent } from './calculations.js'
import { bufferVisualTarget } from './bufferAnimation.js'

const finite = (value) => {
  const number = Number(value)
  return Number.isFinite(number) ? number : 0
}

const negativeCurrency = (value) => currency(-Math.abs(finite(value)))
const clamp = (value, min, max) => Math.min(max, Math.max(min, value))
const prefersReducedMotion = () => (
  typeof window !== 'undefined'
  && typeof window.matchMedia === 'function'
  && window.matchMedia('(prefers-reduced-motion: reduce)').matches
)

function SummaryRows({ rows }) {
  return <div className="overview-summary-rows">{rows.map(([label, value, tone = 'default']) => (
    <div key={label} className={tone === 'warn' ? 'warn' : tone === 'positive' ? 'positive' : ''}>
      <span>{label}</span>
      <b>{value}</b>
    </div>
  ))}</div>
}

function BufferRing({ portfolio, large = false }) {
  const visual = bufferVisualTarget(portfolio.cashHeld, portfolio.safeCashNeeded)
  const progress = clamp(finite(visual.progress), 0, 100)
  return <div
    className={`overview-buffer-ring ${large ? 'large' : ''}`}
    style={{ '--buffer-progress': `${progress}%`, '--buffer-colour': visual.colour }}
    aria-label={`${finite(portfolio.bufferMonths).toFixed(1)} months of cash buffer`}
  >
    <div>
      <strong>{finite(portfolio.bufferMonths).toFixed(1)}</strong>
      <span>months</span>
    </div>
  </div>
}

function LedgerRow({ label, note, value, total = false, tone = 'default' }) {
  return <div className={`overview-insight-ledger-row ${total ? 'total' : ''} ${tone}`}>
    <span>
      <b>{label}</b>
      {note && <small>{note}</small>}
    </span>
    <strong>{value}</strong>
  </div>
}

function CashFlowDetail({ portfolio, settings }) {
  const scenario = portfolio.scenarios?.[0] || {}
  const isCompany = settings.accountType !== 'private'
  return <>
    <p className="overview-insight-explainer">
      {isCompany
        ? 'Combined monthly cash generated by the portfolio: company bank cash after conservative operating allowances and estimated corporation tax, plus cash extracted from the company.'
        : 'Conservative monthly property cash flow after operating allowances and estimated property income tax.'}
    </p>
    <div className="overview-insight-ledger">
      <LedgerRow label="Scheduled rent" note="Current monthly rent before the conservative void allowance" value={currency(portfolio.rent)} />
      <LedgerRow label="Void allowance" note="Conservative rent not expected to be collected" value={negativeCurrency(scenario.voidLoss)} />
      <LedgerRow label="Property fixed costs" note="Mortgage interest, factors, compliance and finance administration" value={negativeCurrency(portfolio.propertyFixedCosts)} />
      {finite(scenario.management) > 0 && <LedgerRow label="Management" note="Rent-linked management charge in this scenario" value={negativeCurrency(scenario.management)} />}
      <LedgerRow label="Repair & appliance reserve" note="Conservative monthly problem-cost allowance" value={negativeCurrency(scenario.problemBudget)} />
      {isCompany && <LedgerRow label="Company costs" note="Enabled recurring company overheads" value={negativeCurrency(portfolio.companyCosts)} />}
      <LedgerRow
        label={isCompany ? 'Estimated corporation tax' : 'Estimated property income tax'}
        note="Current monthly planning estimate"
        value={negativeCurrency(scenario.tax)}
      />
      <LedgerRow
        total
        tone={finite(scenario.cashflow) >= 0 ? 'positive' : 'warn'}
        label={isCompany ? 'Company + extraction cash' : 'Net monthly cash flow'}
        value={currency(scenario.cashflow)}
      />
    </div>
    {isCompany && <div className="overview-insight-split">
      <div><span>Company bank cash flow</span><strong>{currency(scenario.bankCashflow)}</strong><small>After extraction leaves the company</small></div>
      <div><span>Cash extracted</span><strong>{currency(portfolio.extractionTotal)}</strong><small>Added back for the combined headline</small></div>
    </div>}
  </>
}

function PositionDetail({ portfolio }) {
  const ltv = portfolio.totalValue ? portfolio.totalLoans / portfolio.totalValue : 0
  return <>
    <p className="overview-insight-explainer">Your current equity position across the properties included in portfolio totals.</p>
    <div className="overview-insight-ledger compact">
      <LedgerRow label="Portfolio value" value={currency(portfolio.totalValue)} />
      <LedgerRow label="Outstanding loans" value={currency(portfolio.totalLoans)} />
      <LedgerRow total label="Total equity" value={currency(portfolio.totalEquity)} tone="positive" />
      <LedgerRow label="Portfolio LTV" value={percent(ltv, 1)} />
    </div>
    <div className="overview-insight-property-list" aria-label="Property equity breakdown">
      {(portfolio.selected || []).map((property) => <div key={property.id || property.name}>
        <span><b>{property.name}</b><small>{property.lender || 'Current property position'}</small></span>
        <span><small>Value</small><b>{currency(property.latestValuation)}</b></span>
        <span><small>Loan</small><b>{currency(property.loanAmount)}</b></span>
        <span><small>Equity</small><b>{currency(property.equity)}</b></span>
      </div>)}
      {!portfolio.selected?.length && <p className="overview-insight-empty">No active properties are included in totals.</p>}
    </div>
  </>
}

function FinancingDetail({ portfolio, settings }) {
  return <>
    <p className="overview-insight-explainer">Weighted average interest rate across active loans, weighted by each property's outstanding loan balance.</p>
    <div className="overview-financing-hero">
      <span>Weighted rate</span>
      <strong>{percent(portfolio.weightedRate, 2)}</strong>
      <small>{percent(settings.rateShock, 2)} model rate shock included</small>
    </div>
    <div className="overview-insight-property-list financing" aria-label="Property financing breakdown">
      {(portfolio.selected || []).map((property) => <div key={property.id || property.name}>
        <span><b>{property.name}</b><small>{property.lender || 'Lender not set'}</small></span>
        <span><small>Loan</small><b>{currency(property.loanAmount)}</b></span>
        <span><small>Rate</small><b>{percent(property.currentRate, 2)}</b></span>
      </div>)}
      {!portfolio.selected?.length && <p className="overview-insight-empty">No active loans are included in the weighted rate.</p>}
    </div>
  </>
}

function BufferDetail({ portfolio, settings }) {
  const monthlyCosts = finite(portfolio.fixedCosts) + finite(portfolio.variableCosts)
  const targetMonths = Math.max(0, finite(settings.bufferMonths))
  const surplus = Math.max(0, finite(portfolio.cashHeld) - finite(portfolio.safeCashNeeded))
  return <>
    <p className="overview-insight-explainer">How many months of the portfolio's current modelled fixed and variable costs are covered by cash held.</p>
    <div className="overview-buffer-detail-hero">
      <BufferRing portfolio={portfolio} large />
      <div>
        <span>Cash held</span><strong>{currency(portfolio.cashHeld)}</strong>
        <span>Configured target</span><strong>{targetMonths.toFixed(1)} months</strong>
      </div>
    </div>
    <div className="overview-insight-ledger compact">
      <LedgerRow label="Monthly costs used" note="Fixed costs + current variable-cost allowance" value={currency(monthlyCosts)} />
      <LedgerRow label="Target cash" note={`${targetMonths.toFixed(1)} months of modelled costs`} value={currency(portfolio.safeCashNeeded)} />
      <LedgerRow label="Current cover" value={`${finite(portfolio.bufferMonths).toFixed(1)} months`} />
      <LedgerRow
        total
        tone={finite(portfolio.extraCashNeeded) > 0 ? 'warn' : 'positive'}
        label={finite(portfolio.extraCashNeeded) > 0 ? 'Additional cash needed' : 'Cash above target'}
        value={currency(finite(portfolio.extraCashNeeded) > 0 ? portfolio.extraCashNeeded : surplus)}
      />
    </div>
  </>
}

function InsightContent({ insight, portfolio, settings }) {
  if (insight === 'cashflow') return <CashFlowDetail portfolio={portfolio} settings={settings} />
  if (insight === 'position') return <PositionDetail portfolio={portfolio} />
  if (insight === 'financing') return <FinancingDetail portfolio={portfolio} settings={settings} />
  return <BufferDetail portfolio={portfolio} settings={settings} />
}

export default function OverviewPortfolioDashboard({ portfolio, settings }) {
  const [activeInsight, setActiveInsight] = useState(null)
  const [closing, setClosing] = useState(false)
  const modalRef = useRef(null)
  const overlayRef = useRef(null)
  const sourceElementRef = useRef(null)
  const sourceRectRef = useRef(null)
  const closeSequenceRef = useRef(0)

  const scenario = portfolio.scenarios?.[0] || {}
  const isCompany = settings.accountType !== 'private'
  const fixedExpenses = finite(portfolio.propertyFixedCosts) + finite(portfolio.companyCosts)
  const variableAllowance = finite(scenario.voidLoss) + finite(scenario.problemBudget) + finite(scenario.management)
  const portfolioLtv = portfolio.totalValue ? portfolio.totalLoans / portfolio.totalValue : 0
  const selected = portfolio.selected || []
  const ratePreview = selected.length <= 3
    ? selected.map((property) => [property.name, percent(property.currentRate, 2)])
    : [
      ...selected.slice(0, 2).map((property) => [property.name, percent(property.currentRate, 2)]),
      [`+${selected.length - 2} more`, `${selected.length} active loans`],
    ]
  const bufferShortfall = finite(portfolio.extraCashNeeded)
  const bufferSurplus = Math.max(0, finite(portfolio.cashHeld) - finite(portfolio.safeCashNeeded))

  const cards = useMemo(() => [
    {
      id: 'cashflow',
      title: 'Monthly Cash Flow',
      value: currency(scenario.cashflow),
      subtitle: isCompany ? 'Company + extraction cash' : 'Conservative net cash flow',
      icon: finite(scenario.cashflow) >= 0 ? ArrowUpRight : ArrowDownRight,
      tone: finite(scenario.cashflow) >= 0 ? 'positive' : 'warning',
      rows: [
        ['Scheduled rent', currency(portfolio.rent)],
        ['Fixed expenses', currency(fixedExpenses)],
        ['Variable allowance', currency(variableAllowance)],
        ['Estimated tax', currency(scenario.tax)],
      ],
    },
    {
      id: 'position',
      title: 'Portfolio Position',
      value: currency(portfolio.totalEquity),
      subtitle: 'Total equity',
      icon: Landmark,
      tone: 'position',
      rows: [
        ['Portfolio value', currency(portfolio.totalValue)],
        ['Loans', currency(portfolio.totalLoans)],
        ['Portfolio LTV', percent(portfolioLtv, 1)],
      ],
    },
    {
      id: 'financing',
      title: 'Financing',
      value: percent(portfolio.weightedRate, 2),
      subtitle: 'Weighted rate',
      icon: TrendingUp,
      tone: 'financing',
      rows: ratePreview.length ? ratePreview : [['Active loans', 'None']],
    },
    {
      id: 'buffer',
      title: 'Safety Buffer',
      value: `${finite(portfolio.bufferMonths).toFixed(1)} months`,
      subtitle: 'Cash cover',
      icon: ShieldCheck,
      tone: bufferShortfall > 0 ? 'buffer-warning' : 'buffer-safe',
      rows: [
        ['Cash held', currency(portfolio.cashHeld)],
        [`Target (${finite(settings.bufferMonths).toFixed(1)} mo)`, currency(portfolio.safeCashNeeded)],
        [bufferShortfall > 0 ? 'Shortfall' : 'Above target', currency(bufferShortfall > 0 ? bufferShortfall : bufferSurplus), bufferShortfall > 0 ? 'warn' : 'positive'],
      ],
    },
  ], [
    bufferShortfall,
    bufferSurplus,
    fixedExpenses,
    isCompany,
    portfolio.cashHeld,
    portfolio.bufferMonths,
    portfolio.rent,
    portfolio.safeCashNeeded,
    portfolio.totalEquity,
    portfolio.totalLoans,
    portfolio.totalValue,
    portfolio.weightedRate,
    portfolioLtv,
    ratePreview,
    scenario.cashflow,
    scenario.tax,
    settings.bufferMonths,
    variableAllowance,
  ])

  const activeCard = cards.find((card) => card.id === activeInsight)
  const ActiveInsightIcon = activeCard?.icon

  const finishClose = (sequence) => {
    if (sequence !== closeSequenceRef.current) return
    const source = sourceElementRef.current
    setActiveInsight(null)
    setClosing(false)
    sourceRectRef.current = null
    requestAnimationFrame(() => source?.focus?.({ preventScroll: true }))
  }

  const closeInsight = () => {
    if (!activeInsight || closing) return
    setClosing(true)
    const sequence = closeSequenceRef.current + 1
    closeSequenceRef.current = sequence

    const panel = modalRef.current
    const overlay = overlayRef.current
    const source = sourceElementRef.current
    const sourceRect = source?.getBoundingClientRect?.() || sourceRectRef.current

    if (!panel || !sourceRect || prefersReducedMotion() || typeof panel.animate !== 'function') {
      finishClose(sequence)
      return
    }

    panel.getAnimations?.().forEach((animation) => {
      try { animation.finish() } catch { animation.cancel() }
    })

    const targetRect = panel.getBoundingClientRect()
    const translateX = sourceRect.left - targetRect.left
    const translateY = sourceRect.top - targetRect.top
    const scaleX = clamp(sourceRect.width / Math.max(1, targetRect.width), 0.12, 1.4)
    const scaleY = clamp(sourceRect.height / Math.max(1, targetRect.height), 0.08, 1.4)
    const sourceRadius = source ? getComputedStyle(source).borderRadius : '18px'

    const panelAnimation = panel.animate([
      { transform: 'translate3d(0,0,0) scale(1,1)', opacity: 1, borderRadius: getComputedStyle(panel).borderRadius },
      { transform: `translate3d(${translateX}px, ${translateY}px, 0) scale(${scaleX}, ${scaleY})`, opacity: 0.28, borderRadius: sourceRadius },
    ], {
      duration: 360,
      easing: 'cubic-bezier(.32,.72,0,1)',
      fill: 'forwards',
    })
    const overlayAnimation = overlay?.animate?.([
      { opacity: 1 },
      { opacity: 0 },
    ], {
      duration: 300,
      easing: 'ease-out',
      fill: 'forwards',
    })

    Promise.allSettled([
      panelAnimation.finished,
      overlayAnimation?.finished || Promise.resolve(),
    ]).then(() => finishClose(sequence))
  }

  const openInsight = (id, event) => {
    if (activeInsight) return
    const source = event.currentTarget
    sourceElementRef.current = source
    sourceRectRef.current = source.getBoundingClientRect()
    closeSequenceRef.current += 1
    setActiveInsight(id)
  }

  useEffect(() => {
    if (!activeInsight) return undefined
    const previousBodyOverflow = document.body.style.overflow
    const previousHtmlOverflow = document.documentElement.style.overflow
    document.body.style.overflow = 'hidden'
    document.documentElement.style.overflow = 'hidden'
    return () => {
      document.body.style.overflow = previousBodyOverflow
      document.documentElement.style.overflow = previousHtmlOverflow
    }
  }, [activeInsight])

  useEffect(() => {
    if (!activeInsight) return undefined
    const handleKeyDown = (event) => {
      if (event.key === 'Escape') closeInsight()
    }
    document.addEventListener('keydown', handleKeyDown)
    return () => document.removeEventListener('keydown', handleKeyDown)
  }, [activeInsight, closing])

  useEffect(() => {
    if (!activeInsight) return undefined
    const frame = requestAnimationFrame(() => {
      const panel = modalRef.current
      const sourceRect = sourceRectRef.current
      panel?.focus?.({ preventScroll: true })
      if (!panel || !sourceRect || prefersReducedMotion() || typeof panel.animate !== 'function') return

      const targetRect = panel.getBoundingClientRect()
      const translateX = sourceRect.left - targetRect.left
      const translateY = sourceRect.top - targetRect.top
      const scaleX = clamp(sourceRect.width / Math.max(1, targetRect.width), 0.12, 1.4)
      const scaleY = clamp(sourceRect.height / Math.max(1, targetRect.height), 0.08, 1.4)
      const sourceRadius = sourceElementRef.current ? getComputedStyle(sourceElementRef.current).borderRadius : '18px'

      panel.animate([
        { transform: `translate3d(${translateX}px, ${translateY}px, 0) scale(${scaleX}, ${scaleY})`, opacity: 0.32, borderRadius: sourceRadius },
        { transform: 'translate3d(0,0,0) scale(1,1)', opacity: 1, borderRadius: getComputedStyle(panel).borderRadius },
      ], {
        duration: 440,
        easing: 'cubic-bezier(.22,1,.36,1)',
        fill: 'both',
      })
    })
    return () => cancelAnimationFrame(frame)
  }, [activeInsight])

  return <>
    <section className="overview-summary-dashboard" aria-label="Portfolio Overview">
      <div className="overview-summary-grid">
        {cards.map((card) => {
          const Icon = card.icon
          const isBuffer = card.id === 'buffer'
          return <button
            key={card.id}
            type="button"
            className={`overview-summary-card overview-summary-${card.id} ${card.tone}`}
            data-open={activeInsight === card.id ? 'true' : 'false'}
            aria-haspopup="dialog"
            aria-expanded={activeInsight === card.id}
            aria-label={`${card.title}: ${card.value}. Open details.`}
            onClick={(event) => openInsight(card.id, event)}
          >
            <span className="overview-summary-card-head">
              <span className="overview-summary-icon"><Icon size={18} strokeWidth={1.8} /></span>
              <span className="overview-summary-title">
                <b>{card.title}</b>
                <strong>{card.value}</strong>
                <small>{card.subtitle}</small>
              </span>
              <span className="overview-summary-info" aria-hidden="true"><CircleHelp size={15} strokeWidth={1.65} /></span>
            </span>
            {isBuffer
              ? <div className="overview-summary-buffer-body"><BufferRing portfolio={portfolio} /><SummaryRows rows={card.rows} /></div>
              : <SummaryRows rows={card.rows} />}
          </button>
        })}
      </div>
    </section>

    {activeCard && <div
      ref={overlayRef}
      className={`overview-insight-overlay ${closing ? 'closing' : ''}`}
      onPointerDown={(event) => {
        if (event.target === event.currentTarget) closeInsight()
      }}
      aria-hidden="false"
    >
      <section
        ref={modalRef}
        className="overview-insight-sheet"
        role="dialog"
        aria-modal="true"
        aria-labelledby={`overview-insight-${activeCard.id}-title`}
        tabIndex={-1}
      >
        <header className="overview-insight-sheet-head">
          <span className="overview-insight-sheet-icon">{ActiveInsightIcon && <ActiveInsightIcon size={20} strokeWidth={1.75} />}</span>
          <span>
            <small>PORTFOLIO OVERVIEW</small>
            <h2 id={`overview-insight-${activeCard.id}-title`}>{activeCard.title}</h2>
          </span>
          <button type="button" className="overview-insight-close" aria-label={`Close ${activeCard.title} details`} onClick={closeInsight}><X size={18} /></button>
        </header>
        <div className="overview-insight-sheet-body">
          <div className="overview-insight-value">
            <strong>{activeCard.value}</strong>
            <span>{activeCard.subtitle}</span>
          </div>
          <InsightContent insight={activeCard.id} portfolio={portfolio} settings={settings} />
        </div>
      </section>
    </div>}
  </>
}

