create extension if not exists pg_net with schema extensions;
create extension if not exists pg_cron with schema pg_catalog;
create extension if not exists supabase_vault with schema vault;

grant usage on schema cron to postgres;
grant all privileges on all tables in schema cron to postgres;

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists push_subscriptions_user_id_idx on public.push_subscriptions(user_id);
alter table public.push_subscriptions enable row level security;
revoke all on table public.push_subscriptions from anon, authenticated;

create table if not exists public.notification_deliveries (
  user_id uuid not null references auth.users(id) on delete cascade,
  event_key text not null,
  cycle_key text not null,
  created_at timestamptz not null default now(),
  primary key (user_id, event_key, cycle_key)
);

create index if not exists notification_deliveries_created_at_idx on public.notification_deliveries(created_at);
alter table public.notification_deliveries enable row level security;
revoke all on table public.notification_deliveries from anon, authenticated;

-- The job is safe to install before secrets exist: the SELECT emits no HTTP request until both
-- named Vault secrets have been created. Re-running this migration updates the named cron job.
select cron.schedule(
  'btl-notification-dispatch',
  '7 * * * *',
  $cron$
    select net.http_post(
      url := (select decrypted_secret from vault.decrypted_secrets where name = 'notification_dispatch_url' limit 1),
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'x-notification-dispatch-secret', (select decrypted_secret from vault.decrypted_secrets where name = 'notification_dispatch_secret' limit 1)
      ),
      body := jsonb_build_object('scheduled_at', now()),
      timeout_milliseconds := 10000
    ) as request_id
    where (select decrypted_secret from vault.decrypted_secrets where name = 'notification_dispatch_url' limit 1) is not null
      and (select decrypted_secret from vault.decrypted_secrets where name = 'notification_dispatch_secret' limit 1) is not null;
  $cron$
);
